[theme]
primaryColor = "#00d09c"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#f0f0f0"
font = "sans serif"

[server]
headless = true
port = 8501
enableStaticServing = true
